name: Build Sphinx Docs for Turbine IG

on:
  push:
    branches:
      - main
    paths:
      - 'docs/turbine_ig/**'
  pull_request:
    branches:
      - main
    paths:
      - 'docs/turbine_ig/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx
        pip install -r ../requirements.txt

    - name: Build documentation
      run: |
        cd docs/turbine_ig
        make html

    - name: Upload HTML
      uses: actions/upload-artifact@v4
      with:
        name: Sphinx-HTML
        path: docs/turbine_ig/_build/html
